"""historical-computation-replay-taxonomy-v2.

Counts repeated historical computations by their *cause*, so a determinism reproduction is never
described as "zero historical recomputation" and is never conflated with a result-conditioned,
rescue or optimization rerun.

The distinction matters because "we re-ran it" is the sentence under which a rescue hides. Re-running
a computation to prove it is deterministic and re-running it because you did not like the number are
opposite acts that produce identical-looking logs.

Definitions:

* result-conditioned rerun  — a repeat or altered run selected AFTER observing an economic result.
* rescue rerun              — a repeat intended to improve or recover a failed result.
* optimization rerun        — a repeat generated by a parameter-search process.
* determinism reproduction  — a byte-identical or semantically identical recomputation used to
  verify reproducibility or reconstruct missing artifacts.
* infrastructure retry      — a repeat caused by CI / process / transport / artifact-write failure
  BEFORE a valid result was accepted.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass

SCHEMA_VERSION = "historical-computation-replay-taxonomy/2.0"


@dataclass(frozen=True)
class ReplayTaxonomy:
    result_conditioned_rerun_count: int
    rescue_rerun_count: int
    optimization_rerun_count: int
    determinism_reproduction_batch_count: int
    determinism_reproduced_scenario_count: int
    infrastructure_retry_count: int
    byte_identical_replay_count: int
    semantic_input_change_count: int

    def to_dict(self) -> dict:
        return asdict(self)


def validate(tax: ReplayTaxonomy) -> None:
    """Raise ``ValueError`` on any impossible combination."""
    for name, val in asdict(tax).items():
        if val < 0:
            raise ValueError(f"{name} must be >= 0, got {val}")
    if (tax.determinism_reproduced_scenario_count > 0
            and tax.determinism_reproduction_batch_count == 0):
        raise ValueError("reproduced scenarios present but zero reproduction batches recorded")
    if tax.byte_identical_replay_count > tax.determinism_reproduced_scenario_count:
        raise ValueError("byte-identical replays cannot exceed reproduced scenarios")


def describes_zero_historical_recomputation(tax: ReplayTaxonomy) -> bool:
    """A determinism reproduction is NOT zero historical recomputation."""
    return (
        tax.determinism_reproduction_batch_count == 0
        and tax.determinism_reproduced_scenario_count == 0
        and tax.result_conditioned_rerun_count == 0
        and tax.rescue_rerun_count == 0
        and tax.optimization_rerun_count == 0
    )


def result_conditioned_total(tax: ReplayTaxonomy) -> int:
    """Reruns that were selected after a result was known — the ones that endanger a verdict."""
    return (tax.result_conditioned_rerun_count
            + tax.rescue_rerun_count
            + tax.optimization_rerun_count)
